# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-06 02:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='部门名称')),
            ],
            options={
                'verbose_name_plural': '部门',
                'verbose_name': '部门',
            },
        ),
        migrations.CreateModel(
            name='OU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=32, unique=True, verbose_name='GUID')),
                ('dn', models.CharField(max_length=255, unique=True, verbose_name='DN')),
                ('name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('hidden', models.BooleanField(default=False, verbose_name='隐藏')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.OU', verbose_name='上级部门')),
            ],
            options={
                'verbose_name_plural': 'AD部门',
                'verbose_name': 'AD部门',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='全名')),
                ('full_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='姓名')),
                ('xing', models.SlugField(default='a', verbose_name='英文姓')),
                ('ming', models.SlugField(default='a', verbose_name='英文名')),
                ('xingming', models.SlugField(default='a', verbose_name='英文姓名')),
                ('jobnumber', models.CharField(blank=True, default='', max_length=6, verbose_name='工号')),
                ('extNumber', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='分机号')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('department', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='部门')),
                ('dn', models.CharField(blank=True, max_length=255, null=True, verbose_name='DN')),
                ('order', models.PositiveIntegerField(default=99999, verbose_name='排序')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Profile', verbose_name='上级经理')),
                ('ou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_profiles', to='base.OU', verbose_name='AD部门')),
                ('root_ou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_profiles', to='base.OU', verbose_name='大部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='域账户')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'verbose_name': '用户信息',
                'ordering': ['order', 'xingming'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, unique=True, verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '用户标签',
                'verbose_name': '用户标签',
            },
        ),
    ]
