# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-06 02:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='应用名称')),
                ('description', models.CharField(max_length=100, verbose_name='应用描述')),
                ('agent_id', models.IntegerField(verbose_name='Agent ID')),
            ],
            options={
                'verbose_name_plural': '钉钉应用',
                'verbose_name': '钉钉应用',
            },
        ),
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='群名称')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='描述')),
                ('chat_id', models.CharField(blank=True, default='', max_length=100, verbose_name='群ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedchatgroups', to=settings.AUTH_USER_MODEL, verbose_name='群主')),
                ('users', models.ManyToManyField(related_name='chatgroups', to=settings.AUTH_USER_MODEL, verbose_name='群成员')),
            ],
            options={
                'verbose_name_plural': '钉钉群',
                'verbose_name': '钉钉群',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='企业名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='企业描述')),
                ('corp_id', models.CharField(max_length=32, verbose_name='Corp ID')),
                ('corp_secret', models.CharField(max_length=64, verbose_name='Corp Secret')),
            ],
            options={
                'verbose_name_plural': '钉钉企业',
                'verbose_name': '钉钉企业',
            },
        ),
        migrations.CreateModel(
            name='DingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='头像')),
                ('ding_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='全局用户ID')),
                ('user_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='企业用户ID')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('aduser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='域账户')),
            ],
            options={
                'verbose_name_plural': '钉钉帐号',
                'verbose_name': '钉钉帐号',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dingding.Company', verbose_name='企业'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('company', 'name'), ('company', 'agent_id')]),
        ),
    ]
